FROM nginx:latest

COPY ./index.html /usr/share/nginx/html/
COPY ./index.html /var/www/html/

RUN chmod +r /usr/share/nginx/html/index.html
RUN chmod +r /var/www/html/index.html


CMD ["nginx", "-g", "daemon off;"]
